# Generated by Django 5.1.4 on 2025-01-13 17:14

import appointment_booking.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Services',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=32)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('short_description', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=4000)),
                ('duration', models.IntegerField()),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=32)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('title', models.IntegerField(default=0)),
                ('full_name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service_Availabilities',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=32)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('day', models.IntegerField()),
                ('start_time', models.IntegerField(default=900)),
                ('end_time', models.IntegerField(default=1800)),
                ('break_duration', models.IntegerField(default=0)),
                ('break_start_time', models.IntegerField(default=1200)),
                ('break_end_time', models.IntegerField(default=1300)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_booking.appointment_services')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service_Providers',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=32)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_description', models.CharField(max_length=512)),
                ('bio', models.CharField(max_length=10000)),
                ('address', models.CharField(max_length=512)),
                ('linkedin', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('tiktok', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('x', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
                ('work_email', models.CharField(max_length=64)),
                ('work_phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=32)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('short_description', models.CharField(max_length=256)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('full_day', models.BooleanField(default=False)),
                ('start_time', models.IntegerField(default=900)),
                ('end_time', models.IntegerField(default=1200)),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_booking.service_providers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(max_length=32)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=4000)),
                ('service_id', models.ForeignKey(on_delete=models.SET(appointment_booking.models.get_sentinel_user), to='appointment_booking.appointment_services')),
                ('customer_id', models.ForeignKey(on_delete=models.SET(appointment_booking.models.get_sentinel_user), to='appointment_booking.customers')),
                ('provider_id', models.ForeignKey(on_delete=models.SET(appointment_booking.models.get_sentinel_user), to='appointment_booking.service_providers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='appointment_services',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment_booking.service_providers'),
        ),
    ]
