# Generated by Django 5.1.4 on 2025-01-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0003_alter_appointment_services_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_providers',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
