# Generated by Django 5.1.4 on 2025-01-15 16:13

import appointment_booking.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_booking', '0005_alter_service_providers_address_and_more'),
        ('service_provider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_services',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.service_providers'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='provider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_provider.service_providers'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='provider_id',
            field=models.ForeignKey(on_delete=models.SET(appointment_booking.models.get_sentinel_user), to='service_provider.service_providers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Service_Providers',
        ),
    ]
